// Package reports implements the report/project HTTP API: project
// create/list and immutable report append/list. Reports are append-only by
// contract; no update or delete routes exist.
package reports

import (
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"net/http"
	"strconv"

	"warden/internal/model"
	"warden/internal/server"
	"warden/internal/server/audit"
	"warden/internal/store"
)

// maxBodyBytes bounds API request bodies.
const maxBodyBytes = 1 << 20 // 1 MiB

var (
	errInvalidJSON     = errors.New("request body must be a single JSON object with known fields")
	errPayloadTooLarge = errors.New("request body exceeds the size limit")
)

// Handler serves the report and project routes.
type Handler struct {
	store *store.Store
	audit *audit.Recorder
}

// New returns a Handler backed by the store and audit recorder.
func New(s *store.Store, a *audit.Recorder) *Handler {
	return &Handler{store: s, audit: a}
}

// Register mounts all report/project routes on mux.
func (h *Handler) Register(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/v1/projects", h.createProject)
	mux.HandleFunc("GET /api/v1/projects", h.listProjects)
	mux.HandleFunc("POST /api/v1/reports", h.createReport)
	mux.HandleFunc("GET /api/v1/projects/{name}/reports", h.listReports)
}

// record writes an audit event and surfaces recorder failures as a server
// warning so audit loss is never silent. It never includes report contents
// (title/summary) in metadata.
func (h *Handler) record(r *http.Request, op, resourceType, resourceID, result string, err error, metadata map[string]any) {
	if aerr := h.audit.RecordRequest(r.Context(), r, op, resourceType, resourceID, result, err, metadata); aerr != nil {
		slog.Warn("audit write failed",
			"op", op,
			"resource_type", resourceType,
			"resource_id", resourceID,
			"error", aerr,
		)
	}
}

// createProject creates a project or returns the existing one (idempotent),
// giving a stable identifier for a given name.
func (h *Handler) createProject(w http.ResponseWriter, r *http.Request) {
	var req model.ProjectRequest
	if err := decodeStrict(w, r, &req); err != nil {
		h.record(r, "project.create", "project", "", "failure", err, nil)
		writeDecodeError(w, err)
		return
	}
	p, err := h.store.CreateProject(r.Context(), req.Name)
	if err != nil {
		h.record(r, "project.create", "project", "", "failure", err, nil)
		writeStoreError(w, err)
		return
	}
	h.record(r, "project.create", "project", req.Name, "success", nil,
		map[string]any{"name": p.Name})
	server.WriteJSON(w, http.StatusCreated, p)
}

// listProjects returns all projects ordered by name.
func (h *Handler) listProjects(w http.ResponseWriter, r *http.Request) {
	projects, err := h.store.ListProjects(r.Context())
	if err != nil {
		h.record(r, "project.list", "project", "", "failure", err, nil)
		server.WriteError(w, http.StatusInternalServerError, server.ErrInternal, "list projects failed")
		return
	}
	if projects == nil {
		projects = []model.Project{}
	}
	h.record(r, "project.list", "project", "", "success", nil, nil)
	server.WriteJSON(w, http.StatusOK, projects)
}

// createReport appends an immutable report entry. CreatedAt is generated by
// the server. Audit metadata carries the project name and agent model but
// never the title or summary.
func (h *Handler) createReport(w http.ResponseWriter, r *http.Request) {
	var req model.ReportRequest
	if err := decodeStrict(w, r, &req); err != nil {
		h.record(r, "report.create", "report", "", "failure", err, nil)
		writeDecodeError(w, err)
		return
	}
	report, err := h.store.CreateReport(r.Context(), req.Project, req.Title, req.Summary, req.AgentModel)
	if err != nil {
		h.record(r, "report.create", "report", "", "failure", err, nil)
		writeStoreError(w, err)
		return
	}
	h.record(r, "report.create", "report", strconv.FormatInt(report.ID, 10), "success", nil,
		map[string]any{
			"project":     req.Project,
			"agent_model": req.AgentModel,
		})
	server.WriteJSON(w, http.StatusCreated, report)
}

// listReports returns report entries for a project in chronological order.
func (h *Handler) listReports(w http.ResponseWriter, r *http.Request) {
	name := r.PathValue("name")
	reports, err := h.store.ListReports(r.Context(), name)
	if err != nil {
		h.record(r, "report.list", "report", name, "failure", err, nil)
		writeStoreError(w, err)
		return
	}
	if reports == nil {
		reports = []model.Report{}
	}
	h.record(r, "report.list", "report", name, "success", nil,
		map[string]any{"project": name})
	server.WriteJSON(w, http.StatusOK, reports)
}

// decodeStrict enforces a bounded body, strict JSON decoding with no unknown
// fields, and exactly one JSON object.
func decodeStrict(w http.ResponseWriter, r *http.Request, dst any) error {
	r.Body = http.MaxBytesReader(w, r.Body, maxBodyBytes)
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(dst); err != nil {
		var maxErr *http.MaxBytesError
		if errors.As(err, &maxErr) {
			return errPayloadTooLarge
		}
		return errInvalidJSON
	}
	if err := dec.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		return errInvalidJSON
	}
	return nil
}

func writeDecodeError(w http.ResponseWriter, err error) {
	if errors.Is(err, errPayloadTooLarge) {
		server.WriteError(w, http.StatusRequestEntityTooLarge, server.ErrPayloadTooLarge, err.Error())
		return
	}
	server.WriteError(w, http.StatusBadRequest, server.ErrInvalidRequest, err.Error())
}

// writeStoreError maps store sentinels to stable HTTP error codes.
func writeStoreError(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, store.ErrNotFound):
		server.WriteError(w, http.StatusNotFound, server.ErrNotFound, "resource not found")
	case errors.Is(err, store.ErrValidation):
		server.WriteError(w, http.StatusBadRequest, server.ErrValidation, err.Error())
	case errors.Is(err, store.ErrDuplicate):
		server.WriteError(w, http.StatusConflict, server.ErrConflict, "resource already exists")
	default:
		server.WriteError(w, http.StatusInternalServerError, server.ErrInternal, "internal server error")
	}
}
