package model

import "time"

// AuditEvent records a server-side operation. CreatedAt is generated by the
// server. Fields never carry credentials, SQL text, or remote command text.
type AuditEvent struct {
	ID           int64
	Operation    string
	ResourceType string
	ResourceID   string
	Source       string
	Result       string
	Error        string
	Metadata     string // JSON text
	CreatedAt    time.Time
}
