package model

import "time"

// Project is a stable report project identifier.
type Project struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Report is an immutable, append-only release-style changelog entry.
// CreatedAt is always generated by the server, never by the caller.
type Report struct {
	ID         int64     `json:"id"`
	Project    string    `json:"project"`
	Title      string    `json:"title"`
	Summary    string    `json:"summary"`
	AgentModel string    `json:"agent_model"`
	CreatedAt  time.Time `json:"created_at"`
}

// ProjectRequest is the write payload for creating (or idempotently
// retrieving) a project.
type ProjectRequest struct {
	Name string `json:"name"`
}

// ReportRequest is the write payload for appending a report entry. The
// caller supplies project, title, summary, and agent_model; created_at is
// always assigned by the server.
type ReportRequest struct {
	Project    string `json:"project"`
	Title      string `json:"title"`
	Summary    string `json:"summary"`
	AgentModel string `json:"agent_model"`
}
