package model

import "time"

// Project is a stable report project identifier.
type Project struct {
	ID   int64
	Name string
}

// Report is an immutable, append-only release-style changelog entry.
// CreatedAt is always generated by the server, never by the caller.
type Report struct {
	ID         int64
	Project    string // project name
	Title      string
	Summary    string
	AgentModel string
	CreatedAt  time.Time
}
