package store

import (
	"context"
	"fmt"

	"warden/internal/model"
)

// AppendAudit records an audit event. CreatedAt is generated by the server;
// caller-supplied values are ignored.
func (s *Store) AppendAudit(ctx context.Context, e model.AuditEvent) error {
	_, err := s.db.ExecContext(ctx, `
		INSERT INTO audit_events
			(operation, resource_type, resource_id, source, result, error, metadata, created_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
		e.Operation, e.ResourceType, e.ResourceID, e.Source, e.Result, e.Error,
		e.Metadata, nowUTC())
	if err != nil {
		return fmt.Errorf("append audit event: %w", err)
	}
	return nil
}
