package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"regexp"
	"strings"

	"warden/internal/model"
)

var (
	projectNameRe   = regexp.MustCompile(`^[A-Za-z0-9._-]{1,100}$`)
	maxTitleBytes   = 200
	maxSummaryBytes = 16384
	maxAgentBytes   = 200
)

// CreateProject creates a project or returns the existing one, giving a
// stable identifier for a given name.
func (s *Store) CreateProject(ctx context.Context, name string) (model.Project, error) {
	if err := validateProjectName(name); err != nil {
		return model.Project{}, fmt.Errorf("%w: %v", ErrValidation, err)
	}
	_, err := s.db.ExecContext(ctx, "INSERT INTO projects (name) VALUES (?)", name)
	if err != nil {
		// Unique violation means it already exists; fall through to lookup.
		if !isUniqueViolation(err) {
			return model.Project{}, fmt.Errorf("insert project: %w", err)
		}
	}
	return s.GetProjectByName(ctx, name)
}

func (s *Store) GetProjectByName(ctx context.Context, name string) (model.Project, error) {
	var p model.Project
	err := s.db.QueryRowContext(ctx, "SELECT id, name FROM projects WHERE name = ?", name).
		Scan(&p.ID, &p.Name)
	if errors.Is(err, sql.ErrNoRows) {
		return model.Project{}, ErrNotFound
	}
	if err != nil {
		return model.Project{}, fmt.Errorf("scan project: %w", err)
	}
	return p, nil
}

func (s *Store) ListProjects(ctx context.Context) ([]model.Project, error) {
	rows, err := s.db.QueryContext(ctx, "SELECT id, name FROM projects ORDER BY name")
	if err != nil {
		return nil, fmt.Errorf("list projects: %w", err)
	}
	defer rows.Close()

	var projects []model.Project
	for rows.Next() {
		var p model.Project
		if err := rows.Scan(&p.ID, &p.Name); err != nil {
			return nil, fmt.Errorf("scan project: %w", err)
		}
		projects = append(projects, p)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return projects, nil
}

// CreateReport appends an immutable report entry. CreatedAt is always
// generated by the server in UTC; the caller cannot set it. The project is
// auto-created when missing.
func (s *Store) CreateReport(ctx context.Context, project, title, summary, agentModel string) (model.Report, error) {
	if err := validateProjectName(project); err != nil {
		return model.Report{}, fmt.Errorf("%w: %v", ErrValidation, err)
	}
	if err := validateReportFields(title, summary, agentModel); err != nil {
		return model.Report{}, fmt.Errorf("%w: %v", ErrValidation, err)
	}

	p, err := s.CreateProject(ctx, project)
	if err != nil {
		return model.Report{}, err
	}

	ts := nowUTC()
	res, err := s.db.ExecContext(ctx, `
		INSERT INTO reports (project_id, title, summary, agent_model, created_at)
		VALUES (?, ?, ?, ?, ?)`,
		p.ID, title, summary, agentModel, ts)
	if err != nil {
		return model.Report{}, fmt.Errorf("insert report: %w", err)
	}
	id, err := res.LastInsertId()
	if err != nil {
		return model.Report{}, fmt.Errorf("last insert id: %w", err)
	}

	createdAt, err := parseTime(ts)
	if err != nil {
		return model.Report{}, fmt.Errorf("parse created_at: %w", err)
	}
	return model.Report{
		ID:         id,
		Project:    project,
		Title:      title,
		Summary:    summary,
		AgentModel: agentModel,
		CreatedAt:  createdAt,
	}, nil
}

// ListReports returns report entries for a project in chronological order.
func (s *Store) ListReports(ctx context.Context, project string) ([]model.Report, error) {
	p, err := s.GetProjectByName(ctx, project)
	if errors.Is(err, ErrNotFound) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}

	rows, err := s.db.QueryContext(ctx, `
		SELECT id, title, summary, agent_model, created_at
		FROM reports WHERE project_id = ? ORDER BY id ASC`, p.ID)
	if err != nil {
		return nil, fmt.Errorf("list reports: %w", err)
	}
	defer rows.Close()

	var reports []model.Report
	for rows.Next() {
		var r model.Report
		var createdAt string
		if err := rows.Scan(&r.ID, &r.Title, &r.Summary, &r.AgentModel, &createdAt); err != nil {
			return nil, fmt.Errorf("scan report: %w", err)
		}
		r.CreatedAt, err = parseTime(createdAt)
		if err != nil {
			return nil, fmt.Errorf("parse report created_at: %w", err)
		}
		r.Project = project
		reports = append(reports, r)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return reports, nil
}

func validateProjectName(name string) error {
	if !projectNameRe.MatchString(name) {
		return fmt.Errorf("invalid project name %q: must match [A-Za-z0-9._-]{1,100}", name)
	}
	return nil
}

func validateReportFields(title, summary, agentModel string) error {
	if title == "" || len(title) > maxTitleBytes {
		return fmt.Errorf("title must be 1-%d UTF-8 bytes", maxTitleBytes)
	}
	if summary == "" || len(summary) > maxSummaryBytes {
		return fmt.Errorf("summary must be 1-%d UTF-8 bytes", maxSummaryBytes)
	}
	if agentModel == "" || len(agentModel) > maxAgentBytes {
		return fmt.Errorf("agent_model must be 1-%d UTF-8 bytes", maxAgentBytes)
	}
	return nil
}

func isUniqueViolation(err error) bool {
	// modernc.org/sqlite reports constraint violations as strings containing
	// "UNIQUE constraint failed". Use a defensive substring match.
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "unique constraint failed") || strings.Contains(msg, "constraint failed")
}
